---
- name: "Utils | Yq :: remove python version"
  ansible.builtin.pip:
    name: yq
    state: absent
    umask: "0022"
  tags:
    - utils
    - yq

- name: "Utils | Yq :: remove apt version"
  ansible.builtin.apt:
    name: yq
    state: absent
  tags:
    - utils
    - yq

- name: "Utils | Yq :: download"
  ansible.builtin.get_url:
    url: https://github.com/{{ repo }}/releases/download/v{{ version }}/yq_linux_amd64
    dest: /usr/local/bin/yq
    owner: root
    group: root
    mode: 0755
    checksum: sha256:{{ checksum }}
  tags:
    - utils
    - yq
