---
- name: "Special | VLC :: installation"
  ansible.builtin.apt:
    name: vlc
    state: latest
  tags:
    - never
    - special
    - vlc

- name: "Special | VLC :: favorite"
  tags:
    - never
    - special
    - vlc
  block:
    - name: "Special | VLC :: favorite [1/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: true
      become_user: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "Special | VLC :: favorite [2/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('vlc.desktop') }}"
      become: true
      become_user: "{{ username }}"
      changed_when: false
