---
- name: "special | VLC :: installation"
  apt:
    name: vlc
    state: latest
  when: wsl == "0"
  tags:
  - never
  - special
  - vlc

- name: "special | VLC :: favorite"
  block:

  - name: "special | VLC :: favorite [1/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      state: read
    become: "{{ username }}"
    register: favorites
    changed_when: false

  - name: "special | VLC :: favorite [2/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      value: "{{ favorites.value | list_append('vlc.desktop') }}"
    become: "{{ username }}"
    changed_when: false

  when: wsl == "0"
  tags:
  - never
  - special
  - vlc
