---
- name: "SCM | git-cliff :: check version"
  ansible.builtin.command:
    cmd: /usr/local/bin/git-cliff --version
  ignore_errors: true
  no_log: true
  register: git_cliff_version
  changed_when: false
  tags:
    - scm
    - git-cliff

- name: "SCM | git-cliff :: download"
  ansible.builtin.get_url:
    url: https://github.com/{{ repo }}/releases/download/v{{ version }}/git-cliff-{{ version }}-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ dlcache }}/git-cliff-v{{ version }}.linux-amd64.tar.gz"
    checksum: sha512:{{ checksum }}
    mode: 0644
  when: git_cliff_version is failed or version|string not in git_cliff_version.stdout
  tags:
    - scm
    - git-cliff

- name: "SCM | git-cliff :: installation"
  ansible.builtin.unarchive:
    src: "{{ dlcache }}/git-cliff-v{{ version }}.linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
      - git-cliff-{{ version }}/git-cliff
    copy: false
  when: git_cliff_version is failed or version|string not in git_cliff_version.stdout
  tags:
    - scm
    - git-cliff

- name: "SCM | git-cliff :: create man folder"
  ansible.builtin.file:
    path: /usr/local/man/man1
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - scm
    - git-cliff

- name: "SCM | git-cliff :: installation (man)"
  ansible.builtin.unarchive:
    src: "{{ dlcache }}/git-cliff-v{{ version }}.linux-amd64.tar.gz"
    dest: /usr/local/man/man1
    extra_opts:
      - --strip-components=2
      - git-cliff-{{ version }}/man/git-cliff.1
    copy: false
  when: git_cliff_version is failed or version|string not in git_cliff_version.stdout
  tags:
    - scm
    - git-cliff

- name: "SCM | git-cliff :: set permission"
  ansible.builtin.file:
    path: /usr/local/bin/git-cliff
    owner: root
    group: root
    mode: 0755
  tags:
    - scm
    - git-cliff
