---
- name: "kubernetes | helm :: check"
  command: helm version --short
  ignore_errors: yes
  register: helm_version
  changed_when: false
  tags:
  - kubernetes
  - helm

- name: "kubernetes | helm :: download"
  get_url:
    url: https://get.helm.sh/helm-v{{ version }}-linux-amd64.tar.gz
    dest: "{{ dlcache }}/helm-{{ version }}.tar.gz"
    sha256sum: "{{ checksum }}"
  when: helm_version is failed or version not in helm_version.stdout_lines[0]
  tags:
  - kubernetes
  - helm

- name: "kubernetes | helm :: unarchive"
  unarchive:
    src: "{{ dlcache }}/helm-{{ version }}.tar.gz"
    dest: /usr/local/bin
    copy: no
    mode: 0755
    exclude:
    - LICENSE
    - README.md
    extra_opts:
    - --strip-components=1
  when: helm_version is failed or version not in helm_version.stdout_lines[0]
  tags:
  - kubernetes
  - helm
