---
- name: "Kubernetes | helm :: check"
  ansible.builtin.command:
    cmd: helm version --short
  ignore_errors: true
  no_log: true
  register: helm_version
  changed_when: false
  tags:
    - kubernetes
    - helm

- name: "Kubernetes | helm :: download"
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v{{ version }}-linux-amd64.tar.gz
    dest: "{{ dlcache }}/helm-{{ version }}.tar.gz"
    checksum: sha256:{{ checksum }}
    mode: 0644
  when: helm_version is failed or version not in helm_version.stdout_lines[0]
  tags:
    - kubernetes
    - helm

- name: "Kubernetes | helm :: unarchive"
  ansible.builtin.unarchive:
    src: "{{ dlcache }}/helm-{{ version }}.tar.gz"
    dest: /usr/local/bin
    copy: false
    exclude:
      - LICENSE
      - README.md
    extra_opts:
      - --strip-components=1
  when: helm_version is failed or version not in helm_version.stdout_lines[0]
  tags:
    - kubernetes
    - helm

- name: "Kubernetes | helm :: permission"
  ansible.builtin.file:
    path: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0755
  tags:
    - kubernetes
    - helm
