repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: check-added-large-files
  - id: check-executables-have-shebangs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: master
  hooks:
  - id: shellcheck
- repo: https://github.com/ansible/ansible-lint
  rev: master
  hooks:
  - id: ansible-lint
    files: \.(yaml|yml)$
