---
- hosts: localhost
  become: yes

  tasks:
    - name: "Install Ubuntu Mono fonts"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - ubuntu-mono

    - name: Install Gnome Terminal
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - gnome-terminal

    - name: Configure Gnome Terminal (default-size-columns)
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_default_profile }}/{{ item.key }}"
        state: present
        value: "{{ item.value }}"
      with_items:
        - { key: "default-size-columns", value: "120" }
        - { key: "default-size-rows", value: "60" }
        - { key: "use-theme-colors", value: "false" }
        - { key: "foreground-color", value: "'{{ terminal.foreground.color }}'" }
        - { key: "custom-background-color", value: "'{{ terminal.background.color }}'" }
        - { key: "background-color", value: "'{{ terminal.background.color }}'" }
        - { key: "palette", value: "{{ terminal.palette }}" }
        - { key: "use-custom-command", value: "'zsh'" }
        - { key: "custom-command", value: "true" }
        - { key: "use-system-font", value: "false" }
        - { key: "font", value: "'Ubuntu Mono 12'" }
        - { key: "cursor-foreground-color", value: "'{{ terminal.cursor.color }}'" }
        - { key: "cursor-foreground-color", value: "'{{ terminal.cursor.color }}'" }
        - { key: "audible-bell", value: "false" }
        - { key: "use-transparent-background", value: "true" }
        - { key: "use-theme-transparency", value: "false" }
        - { key: "background-transparency-percent", value: "{{ 100 - terminal.background.transparency }}" }
        - { key: "custom-command", value: "'zsh'" }

    - name: "Install Terminator"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - terminator
      tags:
        - terminator

    - name: "Configure Terminator"
      template:
        src: home/.config/terminator/config.j2
        dest: "{{ homedir }}/.config/terminator/config"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600
      tags:
        - terminator

    - name: "Git repository"
      apt_repository:
        repo: ppa:git-core/ppa
        filename: git-core

    - name: "Install Git & Git-flow"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - git-flow

    - name: "Configure Git"
      template:
        src: home/.gitconfig.j2
        dest: "{{ homedir }}/.gitconfig"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600

    - name: "Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: "Install Docker"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker.io
        - docker-compose

    - name: "Install Minikube"
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        owner: root
        group: root
        mode: 0755

    - name: "Node repository"
      apt_repository:
        repo: "deb [arch=amd64] https://deb.nodesource.com/{{ packages.node.repo }} {{ ansible_distribution_release }} main"
        state: present
        filename: nodesource

    - name: "Install Node"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - nodejs

    - name: "Configure Node"
      template:
        src: home/.npmrc.j2
        dest: "{{ homedir }}/.npmrc"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600

    - name: "VS Code repository"
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        filename: vscode

    - name: "Install VS Code"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - code

    - name: "Configure VS Code"
      template:
        src: home/.config/Code/User/{{ item }}
        dest: "{{ homedir }}/.config/Code/User/{{ item }}"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600
      with_items:
        - settings.json
        - keybindings.json

    - name: "Install Vim"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim

    - name: "Configure Vim"
      template:
        src: home/.vimrc.j2
        dest: "{{ homedir }}/.vimrc"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600

    - name: "Install Tmux"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmux
      tags:
        - tmux

    - name: "Configure Tmux"
      template:
        src: home/.tmux.conf.j2
        dest: "{{ homedir }}/.tmux.conf"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600
      tags:
        - tmux

    - name: "Install Zsh"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - zsh

    - name: "Configure Zsh"
      template:
        src: home/.zshrc.j2
        dest: "{{ homedir }}/.zshrc"
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: 0600

    - name: "Install Httpie"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpie

    - name: "Install Wallch"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - wallch


