---
- hosts: localhost
  module_defaults:
    apt:
      force_apt_get: yes
  become: yes
  vars:
  - go_version_expected: "go version go{{ packages.go.version }} linux/amd64"
  - protoc_version_expected: "libprotoc {{ packages.protoc.version }}"

  tasks:
  - name: "settings | locale"
    template:
      src: etc/default/locale.j2
      dest: /etc/default/locale
      mode: "0644"

  - name: "settings | auto-start folder"
    file:
      path: "{{ homedir }}/.config/autostart"
      state: directory
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0700

  - name: "fonts | Cascadia Code :: installation"
    win_chocolatey:
      name: cascadiacode
      state: latest
    when: wsl == "1"
    tags:
    - fonts
    - cascadiacode

  - name: "fonts | Ubuntu Mono :: installation"
    apt:
      name: ubuntu-mono
      state: latest
    when: wsl == "0"
    tags:
    - fonts
    - ubuntu-mono

  - name: "fonts | MesloLGS NF :: folder"
    file:
      path: /usr/share/fonts/truetype/meslo-lgs-nf
      state: directory
      mode: '0755'
    when: wsl == "0"
    tags:
    - fonts
    - meslo

  - name: "fonts | MesloLGS NF :: installation"
    get_url:
      url: https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item.src }}.ttf
      dest: /usr/share/fonts/truetype/meslo-lgs-nf/{{ item.dst }}.ttf
      mode: '0644'
    with_items:
    - { src: "MesloLGS%20NF%20Regular", dst: "meslo-lgs-nf-regular" }
    - { src: "MesloLGS%20NF%20Bold", dst: "meslo-lgs-nf-bold" }
    - { src: "MesloLGS%20NF%20Italic", dst: "meslo-lgs-nf-italic" }
    - { src: "MesloLGS%20NF%20Bold%20Italic", dst: "meslo-lgs-nf-bold-italic" }
    when: wsl == "0"
    tags:
    - fonts
    - meslo

  - name: "terminal | Windows Terminal :: installation"
    win_chocolatey:
      name: microsoft-windows-terminal
      state: latest
    when: wsl == "1"
    tags:
    - terminal
    - windows-terminal

  - name: "terminal | Gnome Terminal :: installation"
    apt:
      name: gnome-terminal
      state: latest
    when: wsl == "0"
    tags:
    - terminal
    - gnome-terminal

  - name: "terminal | Gnome Terminal :: configuration"
    become: "{{ username }}"
    dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_default_profile }}/{{ item.key }}"
      state: present
      value: "{{ item.value }}"
    with_items:
    - { key: "default-size-columns", value: "120" }
    - { key: "default-size-rows", value: "60" }
    - { key: "use-theme-colors", value: "false" }
    - { key: "foreground-color", value: "'{{ terminal.foreground.color }}'" }
    - { key: "custom-background-color", value: "'{{ terminal.background.color }}'" }
    - { key: "background-color", value: "'{{ terminal.background.color }}'" }
    - { key: "palette", value: "{{ terminal.palette }}" }
    - { key: "use-custom-command", value: "true" }
    - { key: "custom-command", value: "'/usr/bin/zsh'" }
    - { key: "use-system-font", value: "false" }
    - { key: "font", value: "'Ubuntu Mono 12'" }
    - { key: "cursor-foreground-color", value: "'{{ terminal.cursor.color }}'" }
    - { key: "cursor-foreground-color", value: "'{{ terminal.cursor.color }}'" }
    - { key: "audible-bell", value: "false" }
    - { key: "use-transparent-background", value: "true" }
    - { key: "use-theme-transparency", value: "false" }
    - { key: "background-transparency-percent", value: "{{ 100 - terminal.background.transparency }}" }
    when: wsl == "0"
    tags:
    - terminal
    - gnome-terminal

  - name: "terminal | Terminator :: installation"
    apt:
      name: terminator
      state: latest
    when: wsl == "0"
    tags:
    - terminal
    - terminator

  - name: "terminal | Terminator :: configuration folder"
    file:
      path: "{{ homedir }}/.config/terminator"
      state: directory
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: '0700'
    when: wsl == "0"
    tags:
    - terminal
    - terminator

  - name: "terminal | Terminator :: configuration"
    template:
      src: home/.config/terminator/config.j2
      dest: "{{ homedir }}/.config/terminator/config"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    when: wsl == "0"
    tags:
    - terminal
    - terminator

  - name: "terminal | Terminator :: favorite"
    block:

    - name: "terminal | Terminator :: favorite [1/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "terminal | Terminator :: favorite [2/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_insert('terminator.desktop', 'firefox.desktop') }}"
      become: "{{ username }}"
      when: favorites.value.find('terminator.desktop') < 0

    when: wsl == "0"
    tags:
    - terminal
    - terminator

  - name: "terminal | Tilda :: installation"
    apt:
      name: tilda
      state: latest
    tags:
    - terminal
    - tilda

  - name: "terminal | Tilda :: folder"
    file:
      path: "{{ homedir }}/.config/tilda"
      state: directory
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: '0700'
    tags:
    - terminal
    - tilda

  - name: "terminal | Tilda :: configuration"
    template:
      src: home/.config/tilda/{{ item }}.j2
      dest: "{{ homedir }}/.config/tilda/{{ item }}"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    with_items:
    - config_0
    - style.css
    tags:
    - terminal
    - tilda

  - name: "terminal | Tilda :: auto-start"
    template:
      src: home/.config/autostart/tilda.desktop.j2
      dest: "{{ homedir }}/.config/autostart/tilda.desktop"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - terminal
    - tilda

  - name: "scm | Git :: repository"
    apt_repository:
      repo: ppa:git-core/ppa
      filename: git-core
      mode: 0644
    tags:
    - scm
    - git

  - name: "scm | Git :: installation"
    apt:
      name: ['git', 'git-flow']
      state: latest
    tags:
    - scm
    - git

  - name: "scm | Git :: configuration"
    template:
      src: home/.gitconfig.j2
      dest: "{{ homedir }}/.gitconfig"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - scm
    - git

  - name: "container | Docker :: repository key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
    - container
    - docker

  - name: "container | Docker :: repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      filename: docker
      mode: 0644
    tags:
    - container
    - docker

  - name: "container | Docker :: cleanup"
    apt:
      name: ['docker', 'docker-engine', 'docker.io']
      state: absent
    tags:
    - container
    - docker

  - name: "container | Docker :: installation"
    apt:
      name: ['docker-ce', 'docker-compose']
      state: latest
    tags:
    - container
    - docker

  - name: "kubernetes | kubectl :: repository key"
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    tags:
    - kubernetes
    - kubectl

  - name: "kubernetes | kubectl :: repository"
    apt_repository:
      repo: "deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main"
      state: present
      filename: kubernetes
      mode: 0644
    tags:
    - kubernetes
    - kubectl

  - name: "kubernetes | kubectl :: installation"
    apt:
      name: kubectl
      state: latest
    tags:
    - kubernetes
    - kubectl

  - name: "kubernetes | k3d :: installation"
    get_url:
      url: https://github.com/{{ packages.k3d.repo }}/releases/download/v{{ packages.k3d.version }}/k3d-{{ packages.k3d.platform }}
      dest: /usr/local/bin/k3d
      owner: root
      group: root
      mode: "0755"
      checksum: sha256:{{ packages.k3d.sha256 }}
    tags:
    - kubernetes
    - k3d

  - name: "kubernetes | SOPS :: installation"
    get_url:
      url: https://github.com/{{ packages.sops.repo }}/releases/download/v{{ packages.sops.version }}/sops-v{{ packages.sops.version }}.linux
      dest: /usr/local/bin/sops
      owner: root
      group: root
      mode: "0755"
      checksum: sha256:{{ packages.sops.sha256 }}
    tags:
    - kubernetes
    - sops

  - name: "lang | Node :: repository key"
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
    tags:
    - lang
    - nodejs

  - name: "lang | Node :: repository"
    apt_repository:
      repo: "deb [arch=amd64] https://deb.nodesource.com/{{ packages.node.pkg_repo }} {{ ansible_distribution_release }} main"
      state: present
      filename: nodesource
      mode: 0644
    tags:
    - lang
    - nodejs

  - name: "lang | Node :: installation"
    apt:
      name: nodejs
      state: latest
    tags:
    - lang
    - nodejs

  - name: "lang | Node :: configuration"
    template:
      src: home/.npmrc.j2
      dest: "{{ homedir }}/.npmrc"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - lang
    - nodejs

  - name: "lang | Go :: check"
    command: /usr/local/go/bin/go version
    ignore_errors: yes
    register: go_version
    changed_when: false
    tags:
    - lang
    - go

  - name: "lang | Go :: download"
    get_url:
      url: https://dl.google.com/go/go{{ packages.go.version }}.linux-amd64.tar.gz
      dest: /usr/local/src/go{{ packages.go.version }}.linux-amd64.tar.gz
      checksum: sha256:{{ packages.go.sha256 }}
    when: go_version is failed or go_version.stdout != go_version_expected
    tags:
    - lang
    - go

  - name: "lang | Go :: cleanup"
    file:
      path: /usr/local/go
      state: absent
    when: go_version is failed or go_version.stdout != go_version_expected
    tags:
    - lang
    - go

  - name: "lang | Go :: installation"
    unarchive:
      src: /usr/local/src/go{{ packages.go.version }}.linux-amd64.tar.gz
      dest: /usr/local
      copy: no
    when: go_version is failed or go_version.stdout != go_version_expected
    tags:
    - lang
    - go

  - name: "lang | Go :: configuration"
    template:
      src: etc/profile.d/{{ item }}.j2
      dest: /etc/profile.d/{{ item }}
      mode: 0644
    with_items:
    - go-bin.sh
    - go-path.sh
    tags:
    - lang
    - go

  - name: "lang | Protoc :: check"
    command: protoc --version
    ignore_errors: yes
    register: protoc_version
    changed_when: false
    tags:
    - lang
    - protoc

  - name: "lang | Protoc :: download"
    get_url:
      url: https://github.com/{{ packages.protoc.repo }}/releases/download/v{{ packages.protoc.version }}/protoc-{{ packages.protoc.version }}-linux-x86_64.zip
      dest: /usr/local/src/protoc-{{ packages.protoc.version }}-linux-x86_64.zip
    when: protoc_version is failed or protoc_version.stdout != protoc_version_expected
    tags:
    - lang
    - protoc

  - name: "lang | Protoc :: temporary extraction folder"
    tempfile:
      state: directory
    register: __protoc_tmp
    when: protoc_version is failed or protoc_version.stdout != protoc_version_expected
    tags:
    - lang
    - protoc

  - name: "lang | Protoc :: extraction"
    unarchive:
      src: /usr/local/src/protoc-{{ packages.protoc.version }}-linux-x86_64.zip
      dest: "{{ __protoc_tmp.path }}"
      copy: no
    when: protoc_version is failed or protoc_version.stdout != protoc_version_expected
    tags:
    - lang
    - protoc

  - name: "lang | Protoc :: installation (binaries)"
    copy:
      src: "{{ __protoc_tmp.path }}/bin/protoc"
      dest: "/usr/local/bin/protoc"
      mode: "0755"
      remote_src: yes
    when: protoc_version is failed or protoc_version.stdout != protoc_version_expected
    tags:
    - lang
    - protoc

  - name: "lang | Protoc :: installation (include folder)"
    file:
      path: "/usr/local/include"
      mode: "0755"
      state: directory
    when: protoc_version is failed or protoc_version.stdout != protoc_version_expected
    tags:
    - lang
    - protoc

  - name: "lang | Protoc :: installation (includes)"
    copy:
      src: "{{ __protoc_tmp.path }}/include/google/"
      dest: "/usr/local/include/google"
      mode: "0755"
      remote_src: True
    when: protoc_version is failed or protoc_version.stdout != protoc_version_expected
    tags:
    - lang
    - protoc

  - name: "editor | Code :: repository key"
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    tags:
    - container
    - docker

  - name: "editor | Code :: repository"
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      state: present
      filename: vscode
      mode: 0644
    when: wsl == "0"
    tags:
    - editor
    - vscode

  - name: "editor | Code :: installation"
    apt:
      name: code
      state: latest
    when: wsl == "0"
    tags:
    - editor
    - vscode

  - name: "editor | Code :: configuration folder"
    file:
      path: "{{ homedir }}/.config/{{ item }}"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      state: directory
      mode: '0700'
    with_items:
    - "Code"
    - "Code/User"
    when: wsl == "0"
    tags:
    - editor
    - vscode

  - name: "editor | Code :: configuration"
    template:
      src: home/.config/Code/User/{{ item }}
      dest: "{{ homedir }}/.config/Code/User/{{ item }}"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    with_items:
    - settings.json
    - keybindings.json
    when: wsl == "0"
    tags:
    - editor
    - vscode

  - name: "editor | Code :: favorite"
    block:

    - name: "editor | Code :: favorite [1/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "editor | Code :: favorite [2/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('code.desktop') }}"
      become: "{{ username }}"
      when: favorites.value.find('code.desktop') < 0

    when: wsl == "0"
    tags:
    - editor
    - vscode

  - name: "editor | Vim :: installation"
    apt:
      name: vim
      state: latest
    tags:
    - editor
    - vim

  - name: "editor | Vim :: configuration"
    template:
      src: home/.vimrc.j2
      dest: "{{ homedir }}/.vimrc"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - editor
    - vim

  - name: "shell | Zsh :: installation"
    apt:
      name: zsh
      state: latest
    tags:
    - shell
    - zsh

  - name: "shell | Zsh :: configuration"
    template:
      src: home/.zshrc.j2
      dest: "{{ homedir }}/.zshrc"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - shell
    - zsh

  - name: "shell | Zsh :: theme"
    copy:
      src: home/.p10k.zsh
      dest: "{{ homedir }}/.p10k.zsh"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - shell
    - zsh

  - name: "utils | Misc :: installation"
    apt:
      name: [ 'figlet', 'lolcat', 'boxes', 'xclip', 'xsel', 'tree' ]
      state: latest
    tags:
    - utils

  - name: "utils | Tmux :: installation"
    apt:
      name: tmux
      state: latest
    tags:
    - utils
    - tmux

  - name: "utils | Tmux :: configuration"
    template:
      src: home/.tmux.conf.j2
      dest: "{{ homedir }}/.tmux.conf"
      owner: "{{ username }}"
      group: "{{ groupname }}"
      mode: 0600
    tags:
    - utils
    - tmux

  - name: "utils | Httpie :: installation"
    pip:
      name: https://github.com/jakubroztocil/httpie/archive/2.1.0.tar.gz
      executable: pip3
      extra_args: --upgrade
      umask: "0022"
      state: latest
    tags:
    - utils
    - httpie

  - name: "utils | Insomnia :: repository key"
    apt_key:
      url: https://insomnia.rest/keys/debian-public.key.asc
      state: present
    tags:
    - utils
    - insomnia

  - name: "utils | Insomnia :: repository"
    apt_repository:
      repo: "deb [arch=amd64] https://dl.bintray.com/getinsomnia/Insomnia /"
      state: present
      filename: insomnia
      mode: 0644
    tags:
    - utils
    - insomnia

  - name: "utils | Insomnia :: installation"
    apt:
      name: insomnia
      state: latest
    tags:
    - utils
    - insomnia

  - name: "utils | Insomnia :: favorite"
    block:

    - name: "utils | Insomnia :: favorite [1/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "utils | Insomnia :: favorite [2/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('insomnia.desktop') }}"
      become: "{{ username }}"
      when: favorites.value.find('insomnia.desktop') < 0

    when: wsl == "0"
    tags:
    - utils
    - insomnia

  - name: "misc | Wallch :: installation"
    apt:
      name: wallch
      state: latest
    when: wsl == "0"
    tags:
    - misc
    - wallch

  - name: "misc | Chrome :: repository key"
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present
    when: wsl == "0"
    tags:
    - misc
    - chrome

  - name: "misc | Chrome :: repository"
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: "google-chrome"
      update_cache: "yes"
    when: wsl == "0"
    tags:
    - misc
    - chrome

  - name: "misc | Chrome :: installation"
    apt:
      name: google-chrome-stable
      state: latest
    when: wsl == "0"
    tags:
    - misc
    - chrome

  - name: "misc | Chrome :: favorite"
    block:

    - name: "misc | Chrome :: favorite [1/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "misc | Chrome :: favorite [2/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_insert('google-chrome.desktop', 'org.gnome.Nautilus.desktop') }}"
      become: "{{ username }}"
      when: favorites.value.find('google-chrome.desktop') < 0

    when: wsl == "0"
    tags:
    - misc
    - chrome

  - name: "special | Spotify :: repository key"
    apt_key:
      url: https://download.spotify.com/debian/pubkey.gpg
      state: present
    when: wsl == "0"
    tags:
    - never
    - special
    - spotify

  - name: "special | Spotify :: repository"
    apt_repository:
      repo: deb [arch=amd64] http://repository.spotify.com stable non-free
      state: present
      filename: "spotify"
    when: wsl == "0"
    tags:
    - never
    - special
    - spotify

  - name: "special | Spotify :: installation"
    apt:
      name: spotify-client
      state: latest
    when: wsl == "0"
    tags:
    - never
    - special
    - spotify

  - name: "special | Spotify :: favorite"
    block:

    - name: "special | Spotify :: favorite [1/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "special | Spotify :: favorite [2/2]"
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('spotify.desktop') }}"
      become: "{{ username }}"
      when: favorites.value.find('spotify.desktop') < 0

    when: wsl == "0"
    tags:
    - misc
    - chrome
