---
- name: "container | vagrant :: check"
  command: vagrant version --version
  ignore_errors: yes
  no_log: true
  register: vagrant_version
  changed_when: false
  tags:
  - container
  - vagrant

- name: "container | vagrant :: download"
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ version }}/vagrant_{{ version }}_linux_amd64.zip
    dest: "{{ dlcache }}/vagrant-{{ version }}-linux-amd64.zip"
    mode: '0644'
  when: vagrant_version is failed or version not in vagrant_version.stdout
  tags:
  - container
  - vagrant

- name: "container | vagrant :: extraction"
  unarchive:
    src: "{{ dlcache }}/vagrant-{{ version }}-linux-amd64.zip"
    dest: /usr/local/bin
  when: vagrant_version is failed or version not in vagrant_version.stdout
  tags:
  - container
  - vagrant

- name: "container | vagrant :: permission"
  file:
    path: /usr/local/bin/vagrant
    owner: root
    group: root
    mode: '0755'
  tags:
  - container
  - vagrant
