---
- name: "lang | Protoc :: check"
  command: protoc --version
  ignore_errors: yes
  no_log: true
  register: protoc_version
  changed_when: false
  tags:
  - lang
  - protoc

- name: "lang | Protoc :: download"
  get_url:
    url: https://github.com/{{ repo }}/releases/download/v{{ version }}/protoc-{{ version }}-linux-x86_64.zip
    dest: "{{ dlcache }}/protoc-{{ version }}-linux-x86_64.zip"
  when: protoc_version is failed or version not in protoc_version.stdout
  tags:
  - lang
  - protoc

- name: "lang | Protoc :: temporary extraction folder"
  tempfile:
    state: directory
  register: __protoc_tmp
  when: protoc_version is failed or version not in protoc_version.stdout
  tags:
  - lang
  - protoc

- name: "lang | Protoc :: extraction"
  unarchive:
    src: "{{ dlcache }}/protoc-{{ version }}-linux-x86_64.zip"
    dest: "{{ __protoc_tmp.path }}"
    copy: no
  when: protoc_version is failed or version not in protoc_version.stdout
  tags:
  - lang
  - protoc

- name: "lang | Protoc :: installation (binaries)"
  copy:
    src: "{{ __protoc_tmp.path }}/bin/protoc"
    dest: "/usr/local/bin/protoc"
    mode: "0755"
    remote_src: yes
  when: protoc_version is failed or version not in protoc_version.stdout
  tags:
  - lang
  - protoc

- name: "lang | Protoc :: installation (include folder)"
  file:
    path: "/usr/local/include"
    mode: "0755"
    state: directory
  when: protoc_version is failed or version not in protoc_version.stdout
  tags:
  - lang
  - protoc

- name: "lang | Protoc :: installation (includes)"
  copy:
    src: "{{ __protoc_tmp.path }}/include/google/"
    dest: "/usr/local/include/google"
    mode: "0755"
    remote_src: True
  when: protoc_version is failed or version not in protoc_version.stdout
  tags:
  - lang
  - protoc
