---
- name: "Special | Variety :: installation"
  ansible.builtin.apt:
    name: variety
    state: latest
  tags:
    - never
    - special
    - variety

- name: "Special | Variety :: Settings folder"
  ansible.builtin.file:
    path: "{{ homedir }}/.config/variety"
    state: directory
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0700
  tags:
    - never
    - special
    - variety

- name: "Special | Variety :: Settings"
  ansible.builtin.template:
    src: home/.config/variety/{{ item }}.j2
    dest: "{{ homedir }}/.config/variety/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  with_items:
    - variety.conf
  tags:
    - never
    - special
    - variety

- name: "Special | Variety :: Settings"
  ansible.builtin.template:
    src: home/.config/variety/{{ item }}.j2
    dest: "{{ homedir }}/.config/variety/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  with_items:
    - .firstrun
  changed_when: false
  tags:
    - never
    - special
    - variety

- name: "Special | Variety :: auto-start"
  ansible.builtin.template:
    src: home/.config/autostart/variety.desktop.j2
    dest: "{{ homedir }}/.config/autostart/variety.desktop"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  tags:
    - never
    - special
    - variety
