---
- name: "special | Variety :: installation"
  apt:
    name: variety
    state: latest
  when: wsl == "0"
  tags:
  - never
  - special
  - variety

- name: "special | Variety :: Settings folder"
  file:
    path: "{{ homedir }}/.config/variety"
    state: directory
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0700
  when: wsl == "0"
  tags:
  - never
  - special
  - variety

- name: "special | Variety :: Settings"
  template:
    src: home/.config/variety/{{ item }}.j2
    dest: "{{ homedir }}/.config/variety/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  with_items:
  - "variety.conf"
  tags:
  - never
  - special
  - variety

- name: "special | Variety :: Settings"
  template:
    src: home/.config/variety/{{ item }}.j2
    dest: "{{ homedir }}/.config/variety/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  with_items:
  - ".firstrun"
  changed_when: false
  tags:
  - never
  - special
  - variety

- name: "special | Variety :: auto-start"
  template:
    src: home/.config/autostart/variety.desktop.j2
    dest: "{{ homedir }}/.config/autostart/variety.desktop"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  tags:
  - never
  - special
  - variety
