---
- name: "editor | Code :: repository key"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
  - editor
  - vscode

- name: "editor | Code :: repository"
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
    mode: 0644
  when: wsl == "0"
  tags:
  - editor
  - vscode

- name: "editor | Code :: installation"
  apt:
    name: code
    state: present
  when: wsl == "0"
  tags:
  - editor
  - vscode

- name: "editor | Code :: configuration folder"
  file:
    path: "{{ homedir }}/.config/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    state: directory
    mode: '0700'
  with_items:
  - "Code"
  - "Code/User"
  when: wsl == "0"
  tags:
  - editor
  - vscode

- name: "editor | Code :: configuration"
  template:
    src: home/.config/Code/User/{{ item }}.j2
    dest: "{{ homedir }}/.config/Code/User/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  with_items:
  - settings.json
  - keybindings.json
  when: wsl == "0"
  tags:
  - editor
  - vscode

- name: "editor | Code :: extensions"
  shell: code --install-extension {{ item }}
  args:
    creates: "{{ homedir }}/.vscode/extensions/{{ item }}-*/package.json"
  become: true
  become_user: "{{ username }}"
  with_items: "{{ extensions }}"
  when: wsl == "0"
  tags:
  - editor
  - vscode

- name: "editor | Code :: favorite"
  block:

  - name: "editor | Code :: favorite [1/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      state: read
    become: true
    become_user: "{{ username }}"
    register: favorites
    changed_when: false

  - name: "editor | Code :: favorite [2/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      value: "{{ favorites.value | list_insert_after('code.desktop', 'com.gexperts.Tilix.desktop') }}"
    become: true
    become_user: "{{ username }}"
    changed_when: false

  when: wsl == "0"
  tags:
  - editor
  - vscode
