---
- name: "kubernetes | sentry :: download"
  get_url:
    url: https://github.com/getsentry/sentry-cli/releases/download/{{ version }}/sentry-cli-Linux-x86_64
    dest: /usr/local/bin/sentry-cli
    mode: 0755
    checksum: sha256:{{ checksum }}
  tags:
  - kubernetes
  - sentry
