---
- name: "Shell | Zsh :: installation"
  ansible.builtin.apt:
    name: zsh
    state: latest

- name: "Shell | Zsh :: configuration"
  ansible.builtin.template:
    src: home/.zshrc.j2
    dest: "{{ homedir }}/.zshrc"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600

- name: "Shell | Zsh :: theme"
  ansible.builtin.template:
    src: home/.p10k.zsh.j2
    dest: "{{ homedir }}/.p10k.zsh"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600

- name: "Shell | Zsh :: custom folder"
  ansible.builtin.file:
    path: "{{ homedir }}/.zsh.custom"
    state: directory
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0750

- name: "Shell | Zsh :: custom plugins"
  ansible.builtin.file:
    path: "{{ homedir }}/.zsh.custom/plugins"
    state: directory
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0750

- name: "Shell | Zsh :: custom scripts"
  ansible.builtin.copy:
    src: "{{ item }}.sh"
    dest: "{{ homedir }}/.zsh.custom/{{ item }}.zsh"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0700
  with_items:
    - 000.aliases
    - 005.path
    - 010.kubeconfig

- name: "Shell | Zsh :: autosuggestions plugin"
  ansible.builtin.file:
    src: "{{ homedir }}/{{ dotdir }}/zsh-autosuggestions"
    dest: "{{ homedir }}/.zsh.custom/plugins/zsh-autosuggestions"
    state: link
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0750

- name: "Shell | Zsh :: syntax-highlighting plugin"
  ansible.builtin.file:
    src: "{{ homedir }}/{{ dotdir }}/zsh-syntax-highlighting"
    dest: "{{ homedir }}/.zsh.custom/plugins/zsh-syntax-highlighting"
    state: link
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0750
