---
- name: "kubernetes | kustomize :: check"
  command: kustomize version
  ignore_errors: yes
  register: kustomize_version
  changed_when: false
  tags:
  - kubernetes
  - kustomize

- name: "kubernetes | kustomize :: download"
  get_url:
    url: https://github.com/{{ repo }}/releases/download/kustomize%2Fv{{ version }}/kustomize_v{{ version }}_{{ platform }}.tar.gz
    dest: "{{ dlcache }}/kustomize-{{ version }}.tar.gz"
    sha256sum: "{{ checksum }}"
  when: kustomize_version is failed or version not in kustomize_version.stdout_lines[0]
  tags:
  - kubernetes
  - kustomize

- name: "kubernetes | kustomize :: unarchive"
  unarchive:
    src: "{{ dlcache }}/kustomize-{{ version }}.tar.gz"
    dest: /usr/local/bin
    copy: no
  when: kustomize_version is failed or version not in kustomize_version.stdout_lines[0]
  tags:
  - kubernetes
  - kustomize

- name: "kubernetes | kustomize :: permission"
  file:
    path: /usr/local/bin/kustomize
    owner: root
    group: root
    mode: '0755'
  tags:
  - kubernetes
  - kustomize
