---
- name: "Kubernetes | kubectl :: repository key"
  ansible.builtin.get_url:
    url: "{{ apt.key }}"
    dest: "{{ keyrings_dir }}/{{ apt.name }}.gpg"
    owner: root
    group: root
    mode: 0644
  tags:
    - kubernetes
    - kubectl

- name: "Kubernetes | kubectl :: repository"
  ansible.builtin.template:
    src: apt.sources.list.j2
    dest: /etc/apt/sources.list.d/{{ apt.name }}.list
    owner: root
    group: root
    mode: 0644
  register: apt_repo
  tags:
    - kubernetes
    - kubectl

- name: "Kubernetes | kubectl :: installation"
  ansible.builtin.apt:
    name:
      - kubectl
    state: present
  tags:
    - kubernetes
    - kubectl
