---
- name: "Kubernetes | kubectl :: repository key"
  ansible.builtin.get_url:
    url: "{{ apt.key }}"
    dest: "{{ keyrings_dir }}/{{ apt.name }}.asc"
    checksum: sha256:{{ apt.sha256 }}
    owner: root
    group: root
    mode: 0644
  register: key_asc
  tags:
    - kubernetes
    - kubectl

- name: "Kubernetes | kubectl :: repository key dearmor"
  ansible.builtin.command:
    cmd: gpg --dearmor --output {{ apt.name }}.gpg {{ apt.name }}.asc
    chdir: "{{ keyrings_dir }}"
    creates: "{{ apt.name }}.gpg"
  when: key_asc.changed
  tags:
    - misc
    - chrome

- name: "Kubernetes | kubectl :: repository"
  ansible.builtin.template:
    src: apt.sources.list.j2
    dest: /etc/apt/sources.list.d/{{ apt.name }}.list
    owner: root
    group: root
    mode: 0644
  register: apt_repo
  tags:
    - kubernetes
    - kubectl

- name: "Kubernetes | kubectl :: installation"
  ansible.builtin.apt:
    name:
      - kubectl
    state: latest
  tags:
    - kubernetes
    - kubectl
