---
- name: "Special | Transmission :: folders"
  ansible.builtin.file:
    path: "{{ homedir }}/{{ item }}"
    state: directory
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0700
  with_items:
    - "Downloads"
    - "Downloads/000 A Traiter 000"
    - "Downloads/.transmission.work"
    - ".config/transmission"
  tags:
    - never
    - special
    - transmission

- name: "Special | Transmission :: installation"
  ansible.builtin.apt:
    name: transmission-gtk
    state: latest
  tags:
    - never
    - special
    - transmission

- name: "Special | Transmission :: settings"
  ansible.builtin.template:
    src: home/.config/transmission/settings.json.j2
    dest: "{{ homedir }}/.config/transmission/settings.json"
    mode: 0644
  tags:
    - never
    - special
    - transmission

- name: "Special | Transmission :: favorite"
  tags:
    - never
    - special
    - transmission
  block:
    - name: "Special | Transmission :: favorite [1/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: true
      become_user: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "Special | Transmission :: favorite [2/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('transmission-gtk.desktop') }}"
      become: true
      become_user: "{{ username }}"
      changed_when: false
