---
- name: "kubernetes | kubeseal :: check"
  command: kubeseal --version
  ignore_errors: yes
  register: kubeseal_version
  changed_when: false
  tags:
  - kubernetes
  - kubeseal

- name: "kubernetes | kubeseal :: download"
  get_url:
    url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ version }}/kubeseal-linux-amd64
    dest: /usr/local/bin/kubeseal
    sha256sum: "{{ checksum }}"
  when: kubeseal_version is failed or version not in kubeseal_version.stdout_lines[0]
  tags:
  - kubernetes
  - kubeseal

- name: "kubernetes | kubeseal :: permission"
  file:
    path: /usr/local/bin/kubeseal
    owner: root
    group: root
    mode: '0755'
  tags:
  - kubernetes
  - kubeseal
