---
- name: "Special | Flameshot :: installation"
  ansible.builtin.apt:
    name: flameshot
    state: present
  tags:
    - never
    - special
    - flameshot

- name: "Special | Flameshot :: favorite"
  tags:
    - never
    - special
    - flameshot
  block:
    - name: "Special | Flameshot :: favorite [1/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: true
      become_user: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "Special | Flameshot :: favorite [2/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('flameshot.desktop') }}"
      become: true
      become_user: "{{ username }}"
      changed_when: false
