---
- name: "SCM | Git :: repository"
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    filename: git
    mode: 0644
  tags:
    - scm
    - git

- name: "SCM | Git :: installation"
  ansible.builtin.apt:
    name:
      - git
      - git-flow
    state: present
  tags:
    - scm
    - git

- name: "SCM | Git :: configuration"
  ansible.builtin.template:
    src: home/.gitconfig.j2
    dest: "{{ homedir }}/.gitconfig"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  tags:
    - scm
    - git
