---
- name: "Misc | Chrome :: repository key"
  ansible.builtin.get_url:
    url: "{{ apt.key }}"
    dest: "{{ keyrings_dir }}/{{ apt.name }}.asc"
    checksum: sha256:{{ apt.sha256 }}
    owner: root
    group: root
    mode: 0644
  register: key_asc
  tags:
    - misc
    - chrome

- name: "Misc | Chrome :: repository key dearmor"
  ansible.builtin.command:
    cmd: gpg --dearmor --output {{ apt.name }}.gpg {{ apt.name }}.asc
    chdir: "{{ keyrings_dir }}"
    creates: "{{ apt.name }}.gpg"
  when: key_asc.changed
  tags:
    - misc
    - chrome

- name: "Misc | Chrome :: repository"
  ansible.builtin.template:
    src: apt.sources.list.j2
    dest: /etc/apt/sources.list.d/{{ apt.name }}.list
    owner: root
    group: root
    mode: 0644
  register: apt_repo
  tags:
    - misc
    - chrome

- name: "Misc | Chrome :: installation"
  ansible.builtin.apt:
    name:
      - google-chrome-stable
      - chrome-gnome-shell
    state: latest
    update_cache: "{{ apt_repo.changed }}"
  tags:
    - misc
    - chrome

- name: "Misc | Chrome :: favorite"
  tags:
    - misc
    - chrome
  block:
    - name: "Misc | Chrome :: favorite [1/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: true
      become_user: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "Misc | Chrome :: favorite [2/2]"
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_insert_after('google-chrome.desktop', 'org.gnome.Nautilus.desktop') }}"
      become: true
      become_user: "{{ username }}"
      changed_when: false
