---
- name: "lang | Go :: check version"
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  no_log: true
  register: go_version
  changed_when: false
  tags:
  - lang
  - go

- name: "lang | Go :: download"
  get_url:
    url: https://dl.google.com/go/go{{ version }}.linux-amd64.tar.gz
    dest: "{{ dlcache }}/go{{ version }}.linux-amd64.tar.gz"
    checksum: sha256:{{ checksum }}
  when: go_version is failed or version|string not in go_version.stdout
  tags:
  - lang
  - go

- name: "lang | Go :: cleanup"
  file:
    path: /usr/local/go
    state: absent
  when: go_version is failed or version|string not in go_version.stdout
  tags:
  - lang
  - go

- name: "lang | Go :: installation"
  unarchive:
    src: "{{ dlcache }}/go{{ version }}.linux-amd64.tar.gz"
    dest: /usr/local
    copy: no
  when: go_version is failed or version|string not in go_version.stdout
  tags:
  - lang
  - go

- name: "lang | Go :: configuration"
  template:
    src: etc/profile.d/{{ item }}.j2
    dest: /etc/profile.d/{{ item }}
    mode: 0644
  with_items:
  - go-bin.sh
  - go-path.sh
  tags:
  - lang
  - go
