---
- name: "Kubernetes | gcloud :: repository key"
  ansible.builtin.get_url:
    url: "{{ apt.key }}"
    dest: "{{ keyrings_dir }}/{{ apt.name }}.gpg"
    owner: root
    group: root
    mode: 0644
  tags:
    - kubernetes
    - gcloud

- name: "Kubernetes | gcloud :: repository"
  ansible.builtin.template:
    src: apt.sources.list.j2
    dest: /etc/apt/sources.list.d/{{ apt.name }}.list
    owner: root
    group: root
    mode: 0644
  register: apt_repo
  tags:
    - kubernetes
    - gcloud

- name: "Kubernetes | gcloud :: installation"
  ansible.builtin.apt:
    name:
      - google-cloud-sdk
    state: latest
    update_cache: "{{ apt_repo.changed }}"
  tags:
    - kubernetes
    - gcloud
