---
- name: "Utils | Tmux :: installation"
  ansible.builtin.apt:
    name: tmux
    state: latest
  tags:
    - utils
    - tmux

- name: "Utils | Tmux :: configuration"
  ansible.builtin.template:
    src: home/.tmux.conf.j2
    dest: "{{ homedir }}/.tmux.conf"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  tags:
    - utils
    - tmux
