---
- name: "terminal | Tilix :: installation"
  apt:
    name: tilix
    state: present

- name: "terminal | Tilix :: alternatives"
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/tilix.wrapper
    priority: 100

- name: "terminal | Tilix :: fix vte issue"
  file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    owner: root
    group: root
    state: link

- name: "terminal | Tilix :: favorite"
  block:

  - name: "terminal | Tilix :: favorite [1/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      state: read
    become: "{{ username }}"
    register: favorites
    changed_when: false

  - name: "terminal | Tilix :: favorite [2/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      value: "{{ favorites.value | list_insert_after('com.gexperts.Tilix.desktop', 'google-chrome.desktop') }}"
    become: "{{ username }}"
    changed_when: false

- name: "terminal | Tilix :: auto-start"
  template:
    src: home/.config/autostart/tilix.desktop.j2
    dest: "{{ homedir }}/.config/autostart/tilix.desktop"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: "0600"

- name: "terminal | Tilix :: config folder"
  file:
    path: "{{ homedir }}/.config/{{ item }}"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    state: directory
    mode: '0700'
  with_items:
  - "tilix"
  - "tilix/schemes"

- name: "terminal | Tilix :: custom theme"
  template:
    src: home/.config/tilix/schemes/dotfiles.json.j2
    dest: "{{ homedir }}/.config/tilix/schemes/dotfiles.json"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: "0600"

- name: "terminal | Tilix :: global preferences"
  dconf:
    key: "/com/gexperts/Tilix/{{ item.key }}"
    value: "{{ item.value }}"
  become: "{{ username }}"
  with_items: "{{ tilix_prefs_global }}"

- name: "terminal | Tilix :: key bindings"
  dconf:
    key: "/com/gexperts/Tilix/keybindings/{{ item.key }}"
    value: "{{ item.value | string }}"
  become: "{{ username }}"
  with_items: "{{ tilix_prefs_keybindings }}"

- name: "terminal | Tilix :: F12 key binding"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.key }}"
    value: "{{ item.value | string }}"
  become: "{{ username }}"
  with_items: "{{ tilix_prefs_hotkey }}"

- name: "terminal | Tilix :: apparence"
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/{{ item.key }}"
    value: "{{ item.value | string }}"
  become: "{{ username }}"
  with_items: "{{ tilix_prefs_apparence }}"

# Tilix configuration + Theme +  extension
# Color themes ~/.config/tilix/schemes/dotfiles.json
