---
- name: "Container | Docker :: repository key"
  ansible.builtin.get_url:
    url: "{{ apt.key }}"
    dest: "{{ keyrings_dir }}/{{ apt.name }}.asc"
    checksum: sha256:{{ apt.sha256 }}
    owner: root
    group: root
    mode: 0644
  register: key_asc
  tags:
    - container
    - docker

- name: "Misc | Docker :: repository key dearmor"
  ansible.builtin.command:
    cmd: gpg --dearmor --output {{ apt.name }}.gpg {{ apt.name }}.asc
    chdir: "{{ keyrings_dir }}"
    creates: "{{ apt.name }}.gpg"
  when: key_asc.changed
  tags:
    - misc
    - chrome

- name: "Container | Docker :: repository"
  ansible.builtin.template:
    src: apt.sources.list.j2
    dest: /etc/apt/sources.list.d/{{ apt.name }}.list
    owner: root
    group: root
    mode: 0644
  register: apt_repo
  tags:
    - container
    - docker

- name: "Container | Docker :: cleanup"
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - docker-compose
    state: absent
  tags:
    - container
    - docker

- name: "Container | Docker :: installation"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: "{{ apt_repo.changed }}"
  tags:
    - container
    - docker

- name: "Container | Docker :: user rights"
  user:
    name: "{{ username }}"
    groups: docker
    createhome: false
    append: true
  tags:
    - container
    - docker
