---
- name: "utils | Insomnia :: remove old repository"
  apt_repository:
    repo: "deb [arch=amd64] https://dl.bintray.com/getinsomnia/Insomnia /"
    state: absent
    filename: insomnia
    mode: 0644
  tags:
  - utils
  - insomnia

- name: "utils | Insomnia :: repository"
  apt_repository:
    repo: "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all"
    state: present
    filename: insomnia
    mode: 0644
  tags:
  - utils
  - insomnia

- name: "utils | Insomnia :: installation"
  apt:
    name: insomnia
    state: present
  tags:
  - utils
  - insomnia

- name: "utils | Insomnia :: favorite"
  block:

  - name: "utils | Insomnia :: favorite [1/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      state: read
    become: "{{ username }}"
    register: favorites
    changed_when: false

  - name: "utils | Insomnia :: favorite [2/2]"
    dconf:
      key: /org/gnome/shell/favorite-apps
      value: "{{ favorites.value | list_append('insomnia.desktop') }}"
    become: "{{ username }}"
    changed_when: false

  when: wsl == "0"
  tags:
  - utils
  - insomnia
