---
- name: "Special | Remmina :: installation"
  ansible.builtin.apt:
    name:
      - remmina
    state: latest
  tags:
    - never
    - special
    - remmina

- name: "Special | Remmina :: favorite"
  tags:
    - never
    - special
    - remmina
  block:
    - name: "Special | Remmina :: favorite [1/2]"
      ansible.builtin.dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: true
      become_user: "{{ username }}"
      register: favorites
      changed_when: false

    - name: "Special | Remmina :: favorite [2/2]"
      ansible.builtin.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{ favorites.value | list_append('org.remmina.Remmina.desktop') }}"
      become: true
      become_user: "{{ username }}"
      changed_when: false
