---
- name: "Editor | Vim :: installation"
  ansible.builtin.apt:
    name: vim
    state: latest
  tags:
    - editor
    - vim

- name: "Editor | Vim :: configuration"
  ansible.builtin.template:
    src: home/.vimrc.j2
    dest: "{{ homedir }}/.vimrc"
    owner: "{{ userid }}"
    group: "{{ groupid }}"
    mode: 0600
  tags:
    - editor
    - vim
