---
- name: "Utils | Syncthing :: repository key"
  ansible.builtin.get_url:
    url: "{{ apt.key }}"
    dest: "{{ keyrings_dir }}/{{ apt.name }}.gpg"
    owner: root
    group: root
    mode: 0644
  tags:
    - utils
    - syncthing

- name: "Utils | Syncthing :: repository"
  ansible.builtin.template:
    src: apt.sources.list.j2
    dest: /etc/apt/sources.list.d/{{ apt.name }}.list
    owner: root
    group: root
    mode: 0644
  register: apt_repo
  tags:
    - utils
    - syncthing

- name: "Utils | Syncthing :: installation"
  ansible.builtin.apt:
    name:
      - syncthing
    state: latest
    update_cache: "{{ apt_repo.changed }}"
  tags:
    - utils
    - syncthing

- name: "Utils | Syncthing :: enable systemd"
  ansible.builtin.systemd:
    name: syncthing@{{ username }}
    enabled: true
    state: started
  tags:
    - utils
    - syncthing

