---
- name: "Fonts | Ubuntu Mono :: installation"
  ansible.builtin.apt:
    name: ubuntu-mono
    state: latest
  tags:
    - fonts
    - ubuntu-mono

- name: "Fonts | Cascadia Code :: remove distribution package"
  ansible.builtin.apt:
    name: fonts-cascadia-code
    state: absent
  tags:
    - fonts
    - cascadiacode

- name: "Fonts | Cascadia Code :: folder"
  ansible.builtin.file:
    path: /usr/share/fonts/truetype/cascadia-code
    state: directory
    mode: 0755
  tags:
    - fonts
    - cascadiacode

- name: "Fonts | Cascadia Code :: download"
  ansible.builtin.get_url:
    url: https://github.com/microsoft/cascadia-code/releases/download/v{{ fonts.cascadia.version }}/CascadiaCode-{{ fonts.cascadia.version }}.zip
    dest: "{{ dlcache }}/CascadiaCode-{{ fonts.cascadia.version }}.zip"
    mode: 0644
  tags:
    - fonts
    - cascadiacode

- name: "Fonts | Cascadia Code :: extraction"
  ansible.builtin.unarchive:
    src: "{{ dlcache }}/CascadiaCode-{{ fonts.cascadia.version }}.zip"
    dest: /usr/share/fonts/truetype/cascadia-code
    copy: false
  tags:
    - fonts
    - cascadiacode

- name: "Fonts | MesloLGS NF :: folder"
  ansible.builtin.file:
    path: /usr/share/fonts/truetype/meslo-lgs-nf
    state: directory
    mode: '0755'
  tags:
    - fonts
    - meslo

- name: "Fonts | MesloLGS NF :: installation"
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item.src }}.ttf
    dest: /usr/share/fonts/truetype/meslo-lgs-nf/{{ item.dst }}.ttf
    mode: '0644'
  with_items:
    - {src: "MesloLGS%20NF%20Regular", dst: "meslo-lgs-nf-regular"}
    - {src: "MesloLGS%20NF%20Bold", dst: "meslo-lgs-nf-bold"}
    - {src: "MesloLGS%20NF%20Italic", dst: "meslo-lgs-nf-italic"}
    - {src: "MesloLGS%20NF%20Bold%20Italic", dst: "meslo-lgs-nf-bold-italic"}
  tags:
    - fonts
    - meslo
